# Generated by Django 5.1.3 on 2025-01-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuer',
            options={'get_latest_by': 'last_updated'},
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'get_latest_by': 'date'},
        ),
        migrations.RemoveField(
            model_name='issuer',
            name='last_updated',
        ),
    ]
